path: D:\python_program\safeY\yolo_server\data
train: D:\python_program\safeY\yolo_server\data\train\images
val: D:\python_program\safeY\yolo_server\data\val\images
test: D:\python_program\safeY\yolo_server\data\test\images
nc: 5
names: [head, ordinary_clothes, person, reflective_vest, safety_helmet]
